chore(vue 3): run unit tests for Vue 3
algolia/vue-instantsearch pull request #1003
Opened 2021-06-14 12:58 UTC by eunjae-lee

## Summary

This PR makes CircleCI run linting and unit tests for Vue 3.

2021-06-14 15:45 UTC, Haroenv commented
looks like the tests on vue 3 still get the vue test utils vue 2:

```
    > 2 | import { mount as mountVue2 } from '@vue/test-utils';
```

2021-06-15 13:59 UTC, Haroenv commented
something is wrong with the babel/jest setup, I think it didn't get applied? 

```
FAIL  src/components/__tests__/ConfigureRelatedItems.js
  ● Test suite failed to run

    Jest encountered an unexpected token

    This usually means that you are trying to import a file which Jest cannot parse, e.g. it's not plain JavaScript.

    By default, if Jest sees a Babel config, it will use that to transform your files, ignoring "node_modules".

    Here's what you can do:
     • If you are trying to use ECMAScript Modules, see https://jestjs.io/docs/en/ecmascript-modules for how to enable it.
     • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
     • If you need a custom transformation specify a "transform" option in your config.
     • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.

    You'll find more details and examples of these config options in the docs:
    https://jestjs.io/docs/en/configuration.html

    Details:

    /home/circleci/vue-instantsearch/jest.setup.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){import { isVue2, Vue2 } from 'vue-demi';
                                                                                             ^^^^^^

    SyntaxError: Cannot use import statement outside a module

      at Runtime.createScriptFromCode (node_modules/jest-runtime/build/index.js:1350:14)
```

2021-06-15 14:20 UTC, eunjae-lee commented
> something is wrong with the babel/jest setup, I think it didn't get applied?

The generated `babel.config.js` on the server was different from what I had in my mac. Fixed in https://github.com/algolia/vue-instantsearch/pull/1003/commits/0e8ab9d8d4443f4e1ad26330c599332fa2c7d82a and now I see the same errors on CircleCI.

2021-06-23 08:01 UTC, Haroenv requested changes
I think it makes more sense to make the CI pass or at least having a list of what's to do to pass CI after this, wdyt?

2021-06-23 08:24 UTC, eunjae-lee commented
> I think it makes more sense to make the CI pass or at least having a list of what's to do to pass CI after this, wdyt?

Yeah it make sense. I'll write a list of todo here by today.

2021-06-24 12:19 UTC, Haroenv commented
Do you prefer having these tests merged & the feat/vue3-compat branch left failing, or waiting until there's a stack with the passing tests?

2021-06-24 13:11 UTC, eunjae-lee commented
> Do you prefer having these tests merged & the feat/vue3-compat branch left failing, or waiting until there's a stack with the passing tests?

Yeah, I wasn't clear. I'd like to get this merged and later create PRs to fix the issues until `feat/vue3-compat` branch becomes green.

2021-06-24 15:35 UTC, Haroenv approved these changes
test setup seems correct

2021-06-24 15:35 UTC, Haroenv commented on test/utils/index.js
> +      wrapper.destroy = () => wrapper.unmount();
```suggestion
      wrapper.destroy = wrapper.unmount;
```

does this work?

2021-06-25 15:48 UTC, eunjae-lee commented on test/utils/index.js
> +      wrapper.destroy = () => wrapper.unmount();
I just tried and it works!

2021-06-25 15:48 UTC, merged