#393 - Feature: pass in the page when emitting the page change event
algolia/vue-instantsearch pull request #394
Opened 2018-02-14 18:14 UTC by VinceG

Related to #393

2018-02-14 18:20 UTC, Haroenv approved these changes
Thank you! Since people didn't expect anything in that callback, we can release this as a patch I think

2018-02-14 18:21 UTC, Haroenv commented
Can you edit the test too? 

https://github.com/algolia/vue-instantsearch/blob/40c9406c5f0d477324a2e9061c75241f6debad6e/src/components/__tests__/pagination.js#L93-L118

2018-02-14 18:29 UTC, VinceG commented
@Haroenv Done.

2018-02-14 19:02 UTC, Haroenv requested changes
Thanks for adding the tests, I think you changed the wrong test though.

2018-02-14 19:02 UTC, Haroenv commented on src/components/__tests__/pagination.js
> +  expect(onPageChange).not.toHaveBeenCalledWith('page');
This should have stayed the same, it's testing that it wasn't called yet

2018-02-14 19:02 UTC, Haroenv commented on src/components/__tests__/pagination.js
>      .getElementsByTagName('li')[3]
after these lines add: 


```js
expect(onPageChange).toHaveBeenCalledWith(page);
```

2018-02-14 19:11 UTC, VinceG commented on src/components/__tests__/pagination.js
>      .getElementsByTagName('li')[3]
@Haroenv  How about this:

```
test('it should emit a "page-change" event when page changes and pass in the page variable', () => {
  const searchStore = {
    page: 1,
    totalPages: 20,
    totalResults: 4000,
  };
  const Component = Vue.extend(Pagination);
  const vm = new Component({
    propsData: {
      searchStore,
    },
  });

  const onPageChange = jest.fn();
  vm.$on('page-change', onPageChange);

  vm.$mount();

  expect(onPageChange).not.toHaveBeenCalled();

  vm.$el
    .getElementsByTagName('li')[3]
    .getElementsByTagName('a')[0]
    .click();
  expect(onPageChange).toHaveBeenCalledTimes(1);

  const page = searchStore.page;
  expect(onPageChange).toHaveBeenCalledWith(page);
  expect(page).toBe(2);
});
```

2018-02-14 22:45 UTC, Haroenv commented on src/components/__tests__/pagination.js
>      .getElementsByTagName('li')[3]
Exactly what I meant!

2018-02-15 08:41 UTC, Haroenv approved these changes
Great! Thanks for your contribution. I’ll release this soon

2018-02-15 08:42 UTC, merged